fix ebay order push
CodistoConnect/CodistoConnect-Magento2 pull request #92
Opened 2022-12-23 04:40 UTC by gksurya0

2023-01-12 05:18 UTC, jlivas requested changes

2023-01-12 05:18 UTC, jlivas commented on Controller/Index/Index.php
> -            $matchedLastName = preg_replace($regexPattern, '', (string)$addressBilling['lastname']);
`$matchedLastName = preg_replace($regexPattern, '', (string)$addressBilling['lastname']) || "_";`

2023-01-12 08:59 UTC, gksurya0 commented on Controller/Index/Index.php
> -            $matchedLastName = preg_replace($regexPattern, '', (string)$addressBilling['lastname']);
above solution always returns 1 as value of $matchedLastName

2023-01-17 05:10 UTC, jlivas approved these changes

2023-01-17 05:10 UTC, merged